export enum OrderStatus {
    WAITING_FOR_PAYMENT = "WAITING_FOR_PAYMENT",
    PAYED = "PAYED",
    WAITING_FOR_APROVEMENT = "WAITING_FOR_APROVEMENT",
    APROVED = "APROVED",
    WAITING_FOR_DELIVERY = "WAITING_FOR_DELIVERY",
    IN_DELIVERY = "IN_DELIVERY",
    ARIVED = "ARIVED",
    ISSUE = "ISSUE",
    IN_VERIFICATION = "IN_VERIFICATION",
}
